### ISSUE TITLE
[Android] impossible to use newGuid() between jni calls

### ISSUE THREAD

**Issue by thedilletante** [graeme-hill/crossguid#23]
Hi! Thank you for the great library again.
I faced the issue that `newGuid()` could not be called between separate jni calls or from different threads. It seems, `AndroidGuidInfo.uuidClass` must be global reference to allow such calls. Also, `JniEnv *` variable should be passed from the current context into `newGuid()` to operate with jni functions to prevent context mismatch.
Is it appropriate to me to open PR with implementation of this behaviour?

**Comment by graeme-hill** [comment]
You're right that the global state will screw you up on multiple threads. You could work around it by sending all the guid creation calls through the same thread like you would do in a lot of java libs when updating a GUI.

I think this is a loss of functionality from a recent change. When you used to have to create a `GuidGenerator` you could pass in the `JNIEnv *` so that would allow you to make one generator per thread each with its own `JNIEnv *`. The reason I made the change is that I wanted to keep it simple on non-android platforms and I wanted to avoid adding any params to `newGuid` because it should be used the same on every platform.

Since this lib already requires c++11 maybe we can just use `thread_local` (I haven't used it before so not 100% on how it works). Something like change this:

```
AndroidGuidInfo androidInfo;
```

to this:

```
thread_local AndroidGuidInfo androidInfo;
```

and then require that you call `initJni` once per thread instead of once globally.

**Comment by graeme-hill** [comment]
I can try this out myself when I get time (not sure when that will be) but I will also accept a PR as long as it doesn't make any change to non-android usage.

**Comment by thedilletante** [comment]
Thank you for quick response and detailed advance.
I fully agree with you that call to `newGuid()` should look the same on every platforms to simplify the usage.
I opened PR to support multithread invocations (https://github.com/graeme-hill/crossguid/pull/24). However, I decided not to use `thread_local` feature (though it would work perfectly) cause I think it would make the usage complicated - the user would have to care of only call to `initJni()` for every thread to use `newGuid()`. So, I implemented `newGuid()` overloading with `JNIEnv` pointer as an argument that should be called with appropriate pointer to the context if `iniJni()` was called from different thread.
I wasn't managed to add reviewers to this PR and link it to this issue, so it would be good if you advise me how to do that.
