### ISSUE TITLE
Android is hard to integrate

### ISSUE THREAD

**Issue by DJHoltkamp** [graeme-hill/crossguid#31]
I am new to Android development and we are doing a cross platform game. I find your instructions to be confusing and it seems much more bloated than other platform integrations. Why don't you simply make a simple implementation and read a string from "/proc/sys/kernel/random/uuid" to avoid all the java integration?

**Comment by graeme-hill** [comment]
Is your problem with the API or actually integrating into your build system? Regarding the API all you have to do is call `initJni()` once before you ever call `newGuid()`.

The goal of this project was to go the opposite direction of other "cross platform" UUID libraries. Instead of implementing one portable guid generator I wanted to use the officially recommended uuid generation technique on the platform. I couldn't find any documentation that says "do not read from `/proc/sys/kernel/random/uuid`, use the java function instead" but from what I read they do recommend the java function. Since Google _seems_ to intend that you do it that way, that is the way I did it.

The libuuid function used on the gnu linux version and the java `randomUUID` function used in the android version are possibly doing what you suggest behind the scenes. The reason I didn't do it directly is to defend against changes in the platform, like if android Q removes `/proc/sys/kernel/random/uuid` or something like that.

The downside to doing it the way you suggest is pretty minor though and I can see the benefit for sure. I wouldn't be opposed to a new mode like `GUID_LINUX_KERNEL` or something like that using your technique. Unless there is some permission issue that stops your from doing that on Android.
